2024-10-22 17:48:38,011 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 27, Function: main]
2024-10-22 17:48:38,016 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 60, Function: setup_socket]
2024-10-22 17:48:38,025 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 62, Function: setup_socket]
2024-10-22 17:48:38,035 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 64, Function: setup_socket]
2024-10-30 18:27:32,490 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 30, Function: main]
2024-10-30 18:27:32,492 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-30 18:27:34,538 - client_logger - ERROR - Connection failed: Error: [WinError 10061] No connection could be made because the target machine actively refused it [File: client_tcp.py, Line: 42, Function: connect]
2024-10-30 18:27:38,579 - client_logger - ERROR - Connection failed: Error: [WinError 10061] No connection could be made because the target machine actively refused it [File: client_tcp.py, Line: 42, Function: connect]
2024-10-30 18:27:42,623 - client_logger - ERROR - Connection failed: Error: [WinError 10061] No connection could be made because the target machine actively refused it [File: client_tcp.py, Line: 42, Function: connect]
2024-10-30 18:27:46,656 - client_logger - ERROR - Connection failed: Error: [WinError 10061] No connection could be made because the target machine actively refused it [File: client_tcp.py, Line: 42, Function: connect]
2024-10-30 18:27:53,685 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-30 18:27:53,687 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-30 18:27:53,689 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 18:27:53,692 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-30 18:27:53,694 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 18:27:53,695 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-30 18:28:51,982 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-30 18:28:51,987 - server_logger - ERROR - Socket setup failed. Error: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted [File: server_tcp.py, Line: 70, Function: setup_socket]
2024-10-30 18:28:51,989 - server_logger - INFO - Server socket closed due to an error. [File: server_tcp.py, Line: 73, Function: setup_socket]
2024-10-30 18:28:51,991 - server_logger - INFO - Server socket was already closed. [File: server_tcp.py, Line: 76, Function: setup_socket]
2024-10-30 18:29:11,046 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-30 18:29:11,051 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-30 18:29:11,052 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 18:29:11,055 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-30 18:29:11,057 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 18:29:11,059 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-30 18:29:51,593 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 30, Function: main]
2024-10-30 18:29:51,594 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-30 18:29:51,595 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-30 18:30:02,156 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 18:30:02,156 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 52238) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 18:30:21,717 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 18:30:21,717 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 52238) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 18:30:21,751 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 18:31:10,000 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-30 18:31:10,005 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-30 18:31:10,007 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 18:31:10,010 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-30 18:31:10,011 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 18:31:10,013 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-30 18:31:13,242 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 30, Function: main]
2024-10-30 18:31:13,248 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-30 18:31:13,251 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-30 18:31:20,105 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 52285) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 18:31:20,105 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 18:34:39,474 - client_logger - ERROR - Failed to send message due to socket error. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 104, Function: build_and_send_message]
2024-10-30 18:34:39,476 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 18:34:39,478 - client_logger - INFO - Logout sent to server. [File: client_tcp.py, Line: 155, Function: logout]
2024-10-30 18:34:39,480 - client_logger - INFO - Client socket closed. [File: client_tcp.py, Line: 160, Function: logout]
2024-10-30 18:35:23,919 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-30 18:35:23,921 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-30 18:35:23,921 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 18:35:23,922 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-30 18:35:23,923 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 18:35:23,924 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-30 18:35:28,937 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 30, Function: main]
2024-10-30 18:35:28,943 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-30 18:35:28,946 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-30 18:40:02,117 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-30 18:40:02,122 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-30 18:40:02,124 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 18:40:02,128 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-30 18:40:02,130 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 18:40:02,132 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-30 18:40:12,947 - client_logger - ERROR - Failed to send message due to socket error. Error: [WinError 10053] An established connection was aborted by the software in your host machine [File: client_tcp.py, Line: 104, Function: build_and_send_message]
2024-10-30 18:40:12,949 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 18:40:12,951 - client_logger - ERROR - Login failed due to connection error: [WinError 10053] An established connection was aborted by the software in your host machine [File: client_tcp.py, Line: 141, Function: login]
2024-10-30 18:40:17,298 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 30, Function: main]
2024-10-30 18:40:17,303 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-30 18:40:17,306 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-30 18:43:32,630 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 18:43:32,630 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 52548) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 18:43:41,272 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 18:43:41,272 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 52548) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 18:43:41,276 - client_logger - INFO - Logout sent to server. [File: client_tcp.py, Line: 155, Function: logout]
2024-10-30 18:43:41,281 - client_logger - INFO - Client socket closed. [File: client_tcp.py, Line: 160, Function: logout]
2024-10-30 18:43:41,316 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 18:43:41,735 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-30 18:43:41,740 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-30 18:43:41,741 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 18:43:41,745 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-30 18:43:41,746 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 18:43:41,749 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-30 18:44:06,344 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 30, Function: main]
2024-10-30 18:44:06,349 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-30 18:44:06,352 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-30 18:44:13,913 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 18:44:23,148 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 52686) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 18:44:49,719 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 18:44:49,722 - client_logger - INFO - Logout sent to server. [File: client_tcp.py, Line: 155, Function: logout]
2024-10-30 18:44:49,724 - client_logger - INFO - Client socket closed. [File: client_tcp.py, Line: 160, Function: logout]
2024-10-30 18:44:49,719 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 52686) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 18:44:53,174 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 18:44:53,607 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-30 18:44:53,612 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-30 18:44:53,614 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 18:44:53,617 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-30 18:44:53,619 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 18:44:53,621 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-30 18:45:13,360 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 30, Function: main]
2024-10-30 18:45:13,365 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-30 18:45:13,368 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-30 18:45:16,690 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 52735) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 18:45:20,911 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 52735) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 18:45:20,911 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 18:45:20,916 - client_logger - INFO - Logout sent to server. [File: client_tcp.py, Line: 155, Function: logout]
2024-10-30 18:45:20,921 - client_logger - INFO - Client socket closed. [File: client_tcp.py, Line: 160, Function: logout]
2024-10-30 18:45:20,956 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 18:48:28,708 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-30 18:48:28,710 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-30 18:48:28,710 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 18:48:28,714 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-30 18:48:28,715 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 18:48:28,717 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-30 18:48:38,682 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 30, Function: main]
2024-10-30 18:48:38,687 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-30 18:48:38,689 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-30 18:48:44,254 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 18:48:56,439 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 52859) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 18:51:35,113 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 18:51:35,119 - client_logger - INFO - Logout sent to server. [File: client_tcp.py, Line: 155, Function: logout]
2024-10-30 18:51:35,125 - client_logger - INFO - Client socket closed. [File: client_tcp.py, Line: 160, Function: logout]
2024-10-30 18:51:35,113 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 52859) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 18:51:43,662 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 18:51:47,699 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-30 18:51:47,704 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-30 18:51:47,705 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 18:51:47,708 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-30 18:51:47,710 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 18:51:47,712 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-30 18:51:52,985 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 30, Function: main]
2024-10-30 18:51:52,991 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-30 18:51:52,994 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-30 18:54:46,301 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 18:54:46,301 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 52960) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 18:55:17,793 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 18:55:17,795 - client_logger - INFO - Logout sent to server. [File: client_tcp.py, Line: 155, Function: logout]
2024-10-30 18:55:17,797 - client_logger - INFO - Client socket closed. [File: client_tcp.py, Line: 160, Function: logout]
2024-10-30 18:55:17,793 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 52960) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 18:55:22,052 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 18:56:21,058 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-30 18:56:21,063 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-30 18:56:21,065 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 18:56:21,068 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-30 18:56:21,070 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 18:56:21,071 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-30 18:56:37,623 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 30, Function: main]
2024-10-30 18:56:37,628 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-30 18:56:37,630 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-30 18:56:43,851 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 18:56:37,631 - server_logger - INFO - New client joined! ('127.0.0.1', 53114) [File: server_tcp.py, Line: 258, Function: server_socket_handaling]
2024-10-30 18:56:51,117 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 53114) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 19:05:56,940 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 19:05:56,942 - client_logger - INFO - Logout sent to server. [File: client_tcp.py, Line: 155, Function: logout]
2024-10-30 19:05:56,944 - client_logger - INFO - Client socket closed. [File: client_tcp.py, Line: 160, Function: logout]
2024-10-30 19:05:56,940 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 53114) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 19:06:02,931 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 19:06:06,538 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-30 19:06:06,544 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-30 19:06:06,545 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 19:06:06,549 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-30 19:06:06,550 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 19:06:06,552 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-30 19:06:10,465 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 30, Function: main]
2024-10-30 19:06:10,470 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-30 19:06:10,473 - server_logger - INFO - New client joined! ('127.0.0.1', 53328) [File: server_tcp.py, Line: 258, Function: server_socket_handaling]
2024-10-30 19:06:10,473 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-30 19:06:15,585 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 53328) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 19:06:15,585 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 19:06:15,648 - client_logger - INFO - username is incorrect try again [File: client_tcp.py, Line: 135, Function: login]
2024-10-30 19:08:32,227 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 53328) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 19:08:32,227 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 19:08:32,229 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 19:08:32,229 - client_logger - INFO - Logout sent to server. [File: client_tcp.py, Line: 159, Function: logout]
2024-10-30 19:08:32,232 - client_logger - INFO - Client socket closed. [File: client_tcp.py, Line: 164, Function: logout]
2024-10-30 19:08:32,649 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-30 19:08:32,654 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-30 19:08:32,656 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 19:08:32,659 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-30 19:08:32,661 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 19:08:32,663 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-30 19:08:58,409 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 30, Function: main]
2024-10-30 19:08:58,414 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-30 19:08:58,416 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-30 19:09:04,266 - client_logger - ERROR - Failed to send message due to socket error. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 104, Function: build_and_send_message]
2024-10-30 19:09:04,268 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 19:09:04,270 - client_logger - ERROR - Failed to connect to 127.0.0.1:5678. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 70, Function: recv_message_and_parse]
2024-10-30 19:09:23,867 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-30 19:09:23,871 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-30 19:09:23,873 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 19:09:23,876 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-30 19:09:23,878 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 19:09:23,880 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-30 19:09:30,548 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 30, Function: main]
2024-10-30 19:09:30,553 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-30 19:09:30,556 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-30 19:09:30,556 - server_logger - INFO - New client joined! ('127.0.0.1', 53454) [File: server_tcp.py, Line: 258, Function: server_socket_handaling]
2024-10-30 19:09:55,148 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
er_socket_handaling]
2024-10-30 19:09:55,215 - client_logger - INFO - username is incorrect try again [File: client_tcp.py, Line: 135, Function: login]
2024-10-30 19:12:37,119 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 19:12:37,121 - client_logger - INFO - Logout sent to server. [File: client_tcp.py, Line: 159, Function: logout]
2024-10-30 19:12:37,123 - client_logger - INFO - Client socket closed. [File: client_tcp.py, Line: 164, Function: logout]
2024-10-30 19:12:37,119 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 53454) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 19:12:40,687 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 19:12:40,696 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 53454) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 19:12:54,330 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 30, Function: main]
2024-10-30 19:12:54,336 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-30 19:12:56,375 - client_logger - ERROR - Connection failed: Error: [WinError 10061] No connection could be made because the target machine actively refused it [File: client_tcp.py, Line: 42, Function: connect]
2024-10-30 19:13:00,432 - client_logger - ERROR - Connection failed: Error: [WinError 10061] No connection could be made because the target machine actively refused it [File: client_tcp.py, Line: 42, Function: connect]
2024-10-30 19:13:03,030 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-30 19:13:03,035 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-30 19:13:03,036 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 19:13:03,040 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-30 19:13:03,042 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 19:13:03,045 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-30 19:13:03,473 - server_logger - INFO - New client joined! ('127.0.0.1', 53546) [File: server_tcp.py, Line: 258, Function: server_socket_handaling]
2024-10-30 19:13:03,473 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-30 19:13:12,153 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
er_socket_handaling]
2024-10-30 19:13:12,211 - client_logger - INFO - username is incorrect try again [File: client_tcp.py, Line: 135, Function: login]
2024-10-30 19:13:19,058 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 53546) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 19:13:19,058 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 19:13:19,067 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 19:14:43,403 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 19:14:43,403 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 53546) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 19:14:43,412 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 19:14:48,262 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 53546) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 19:14:48,270 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 19:14:48,689 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 53546) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 19:14:48,689 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 19:14:48,697 - server_logger - ERROR - Unexpected error: not enough values to unpack (expected 2, got 1) [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 19:14:48,749 - client_logger - INFO - login exceeded maxisum attempts close connection [File: client_tcp.py, Line: 150, Function: login]
2024-10-30 19:14:48,755 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 53546) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 19:14:48,760 - server_logger - ERROR - Unexpected error: 'NoneType' object has no attribute 'split' [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-30 19:14:48,764 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 53546) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 19:14:51,432 - client_logger - ERROR - Failed to send message due to socket error. Error: [WinError 10038] An operation was attempted on something that is not a socket [File: client_tcp.py, Line: 104, Function: build_and_send_message]
2024-10-30 19:14:51,434 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 19:14:51,436 - client_logger - INFO - Logout sent to server. [File: client_tcp.py, Line: 158, Function: logout]
2024-10-30 19:14:51,438 - client_logger - INFO - Client socket closed. [File: client_tcp.py, Line: 163, Function: logout]
2024-10-30 19:14:59,001 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-30 19:14:59,006 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-30 19:14:59,008 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-30 19:14:59,011 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-30 19:14:59,013 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-30 19:14:59,015 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-30 19:15:02,596 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 30, Function: main]
2024-10-30 19:15:02,601 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-30 19:15:02,603 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-30 19:15:02,604 - server_logger - INFO - New client joined! ('127.0.0.1', 53644) [File: server_tcp.py, Line: 258, Function: server_socket_handaling]
2024-10-30 19:15:08,270 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-30 19:15:08,270 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 53644) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-30 19:15:08,335 - client_logger - INFO - username is incorrect try again [File: client_tcp.py, Line: 135, Function: login]
2024-10-30 19:18:39,066 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-30 19:18:39,069 - server_logger - ERROR - Socket setup failed. Error: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted [File: server_tcp.py, Line: 70, Function: setup_socket]
2024-10-30 19:18:39,071 - server_logger - INFO - Server socket closed due to an error. [File: server_tcp.py, Line: 73, Function: setup_socket]
2024-10-30 19:18:39,072 - server_logger - INFO - Server socket was already closed. [File: server_tcp.py, Line: 76, Function: setup_socket]
2024-10-30 19:19:11,783 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-30 19:19:11,786 - server_logger - ERROR - Socket setup failed. Error: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted [File: server_tcp.py, Line: 70, Function: setup_socket]
2024-10-30 19:19:11,787 - server_logger - INFO - Server socket closed due to an error. [File: server_tcp.py, Line: 73, Function: setup_socket]
2024-10-30 19:19:11,787 - server_logger - INFO - Server socket was already closed. [File: server_tcp.py, Line: 76, Function: setup_socket]
2024-10-31 10:46:55,058 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-31 10:46:55,061 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-31 10:46:55,061 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 143, Function: load_user_database]
2024-10-31 10:46:55,063 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-31 10:46:55,063 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 90, Function: load_questions]
2024-10-31 10:46:55,063 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-31 10:47:25,229 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 30, Function: main]
2024-10-31 10:47:25,229 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-31 10:47:25,230 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-31 10:47:25,231 - server_logger - INFO - New client joined! ('127.0.0.1', 58261) [File: server_tcp.py, Line: 258, Function: server_socket_handaling]
2024-10-31 10:47:52,192 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 10:47:52,192 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 58261) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-31 10:47:52,298 - client_logger - INFO - username is incorrect try again [File: client_tcp.py, Line: 135, Function: login]
2024-10-31 10:47:57,254 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 58261) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-31 10:47:57,267 - server_logger - ERROR - Unexpected error: 'NoneType' object has no attribute 'split' [File: server_tcp.py, Line: 442, Function: handle_client_message]
2024-10-31 10:47:57,272 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 58261) [File: server_tcp.py, Line: 264, Function: server_socket_handaling]
2024-10-31 10:48:09,219 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-31 10:48:09,224 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-31 10:48:09,226 - server_logger - ERROR - users.json not found. Starting with an empty users database. [File: server_tcp.py, Line: 146, Function: load_user_database]
2024-10-31 10:48:09,230 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-31 10:48:09,232 - server_logger - ERROR - questions.json not found. Starting with an empty questions bank. [File: server_tcp.py, Line: 92, Function: load_questions]
2024-10-31 10:48:09,233 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-31 10:50:26,942 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 30, Function: main]
2024-10-31 10:50:26,946 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-31 10:50:26,949 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-31 10:50:30,661 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 10:50:26,950 - server_logger - INFO - New client joined! ('127.0.0.1', 58309) [File: server_tcp.py, Line: 261, Function: server_socket_handaling]
2024-10-31 10:50:34,419 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 58309) [File: server_tcp.py, Line: 267, Function: server_socket_handaling]
2024-10-31 10:50:34,473 - client_logger - INFO - username is incorrect try again [File: client_tcp.py, Line: 135, Function: login]
2024-10-31 10:50:38,157 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 58309) [File: server_tcp.py, Line: 267, Function: server_socket_handaling]
2024-10-31 10:50:38,170 - server_logger - ERROR - Unexpected error: 'NoneType' object has no attribute 'split' [File: server_tcp.py, Line: 445, Function: handle_client_message]
2024-10-31 10:50:38,175 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 58309) [File: server_tcp.py, Line: 267, Function: server_socket_handaling]
2024-10-31 10:53:32,762 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 25, Function: main]
2024-10-31 10:53:32,767 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-31 10:53:32,783 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-31 10:53:32,798 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-31 10:53:35,616 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 30, Function: main]
2024-10-31 10:53:35,619 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-31 10:53:35,622 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-31 10:53:35,623 - server_logger - INFO - New client joined! ('127.0.0.1', 58358) [File: server_tcp.py, Line: 261, Function: server_socket_handaling]
2024-10-31 10:53:48,014 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 58358) [File: server_tcp.py, Line: 267, Function: server_socket_handaling]
2024-10-31 10:53:48,066 - client_logger - INFO - login was succsusful [File: client_tcp.py, Line: 130, Function: login]
2024-10-31 10:54:05,285 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 10:54:05,285 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 58358) [File: server_tcp.py, Line: 267, Function: server_socket_handaling]
2024-10-31 10:54:05,291 - server_logger - ERROR - Unexpected error: handle_question_message() missing 1 required positional argument: 'username' [File: server_tcp.py, Line: 445, Function: handle_client_message]
2024-10-31 10:54:05,361 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 58358) [File: server_tcp.py, Line: 267, Function: server_socket_handaling]
2024-10-31 10:54:05,369 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 58358) [File: server_tcp.py, Line: 267, Function: server_socket_handaling]
2024-10-31 11:02:14,236 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 35, Function: main]
2024-10-31 11:02:14,241 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-31 11:02:14,247 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-31 11:02:14,251 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-31 11:05:15,401 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 35, Function: main]
2024-10-31 11:05:15,405 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-31 11:05:59,705 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-31 11:06:19,168 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-31 11:06:53,944 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 39, Function: main]
2024-10-31 11:06:53,945 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-31 11:06:53,946 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-31 11:07:01,697 - server_logger - INFO - New client joined! ('127.0.0.1', 58945) [File: server_tcp.py, Line: 263, Function: server_socket_handaling]
2024-10-31 11:07:12,648 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:07:12,648 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 58945) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:07:12,700 - client_logger - INFO - login was succsusful [File: client_tcp.py, Line: 130, Function: login]
2024-10-31 11:07:48,202 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 58945) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:07:48,202 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:08:41,130 - client_test - ERROR - Failed to connect to 127.0.0.1:5678. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 70, Function: recv_message_and_parse]
2024-10-31 11:09:47,289 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 35, Function: main]
2024-10-31 11:09:47,294 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-31 11:11:19,518 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-31 11:11:22,686 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-31 11:11:44,374 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 39, Function: main]
2024-10-31 11:11:44,375 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-31 11:11:44,377 - server_logger - INFO - New client joined! ('127.0.0.1', 59001) [File: server_tcp.py, Line: 263, Function: server_socket_handaling]
2024-10-31 11:11:44,377 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-31 11:11:53,190 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59001) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:11:53,190 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:11:53,241 - client_logger - INFO - login was succsusful [File: client_tcp.py, Line: 130, Function: login]
2024-10-31 11:12:19,261 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59001) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:12:19,261 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:12:57,582 - client_test - ERROR - Failed to connect to 127.0.0.1:5678. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 70, Function: recv_message_and_parse]
2024-10-31 11:14:21,003 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 35, Function: main]
2024-10-31 11:14:21,008 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-31 11:14:21,015 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-31 11:14:22,638 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-31 11:14:31,461 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 39, Function: main]
2024-10-31 11:14:31,465 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-31 11:14:31,468 - server_logger - INFO - New client joined! ('127.0.0.1', 59043) [File: server_tcp.py, Line: 263, Function: server_socket_handaling]
2024-10-31 11:14:31,467 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-31 11:14:36,299 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59043) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:14:36,299 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:14:36,351 - client_logger - INFO - login was succsusful [File: client_tcp.py, Line: 130, Function: login]
2024-10-31 11:14:38,936 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59043) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:14:38,936 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:15:12,888 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59043) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:15:12,888 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:15:43,611 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59043) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:16:53,393 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 35, Function: main]
2024-10-31 11:16:53,401 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-31 11:16:53,407 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-31 11:16:56,191 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-31 11:17:08,088 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 39, Function: main]
2024-10-31 11:17:08,091 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-31 11:17:08,095 - server_logger - INFO - New client joined! ('127.0.0.1', 59134) [File: server_tcp.py, Line: 263, Function: server_socket_handaling]
2024-10-31 11:17:08,094 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-31 11:17:18,677 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59134) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:17:18,677 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:17:18,735 - client_logger - INFO - login was succsusful [File: client_tcp.py, Line: 130, Function: login]
2024-10-31 11:17:21,777 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59134) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:17:21,777 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:17:33,150 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59134) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:17:33,150 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:19:37,933 - client_test - INFO - error [File: client_tcp.py, Line: 195, Function: qustion_handaling]
2024-10-31 11:20:40,127 - client_test - ERROR - Failed to send message due to socket error. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 104, Function: build_and_send_message]
2024-10-31 11:20:40,129 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:20:40,131 - client_test - INFO - Logout sent to server. [File: client_tcp.py, Line: 157, Function: logout]
2024-10-31 11:20:40,133 - client_test - INFO - Client socket closed. [File: client_tcp.py, Line: 162, Function: logout]
2024-10-31 11:21:41,551 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 35, Function: main]
2024-10-31 11:21:41,557 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-31 11:21:41,562 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-31 11:21:45,939 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-31 11:21:55,940 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 39, Function: main]
2024-10-31 11:21:55,943 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-31 11:21:55,946 - server_logger - INFO - New client joined! ('127.0.0.1', 59238) [File: server_tcp.py, Line: 263, Function: server_socket_handaling]
2024-10-31 11:21:55,946 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-31 11:22:06,131 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59238) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:22:06,130 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:22:14,593 - client_logger - INFO - login was succsusful [File: client_tcp.py, Line: 130, Function: login]
2024-10-31 11:22:18,183 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59238) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:22:18,183 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:22:38,694 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59238) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:22:38,694 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:24:54,241 - client_test - ERROR - Failed to connect to 127.0.0.1:5678. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 70, Function: recv_message_and_parse]
2024-10-31 11:25:11,250 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 35, Function: main]
2024-10-31 11:25:11,256 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-31 11:25:11,262 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-31 11:25:12,813 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-31 11:25:20,398 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 39, Function: main]
2024-10-31 11:25:20,401 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-31 11:25:20,404 - server_logger - INFO - New client joined! ('127.0.0.1', 59309) [File: server_tcp.py, Line: 263, Function: server_socket_handaling]
2024-10-31 11:25:20,403 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-31 11:25:24,442 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59309) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:25:24,442 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:25:24,498 - client_logger - INFO - login was succsusful [File: client_tcp.py, Line: 130, Function: login]
2024-10-31 11:25:26,610 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59309) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:25:26,610 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:27:05,711 - client_test - ERROR - Failed to send message due to socket error. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 104, Function: build_and_send_message]
2024-10-31 11:27:05,713 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:27:05,714 - client_test - ERROR - Failed to connect to 127.0.0.1:5678. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 70, Function: recv_message_and_parse]
2024-10-31 11:27:16,770 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 39, Function: main]
2024-10-31 11:27:16,774 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-31 11:27:18,820 - client_logger - ERROR - Connection failed: Error: [WinError 10061] No connection could be made because the target machine actively refused it [File: client_tcp.py, Line: 42, Function: connect]
2024-10-31 11:27:22,866 - client_logger - ERROR - Connection failed: Error: [WinError 10061] No connection could be made because the target machine actively refused it [File: client_tcp.py, Line: 42, Function: connect]
2024-10-31 11:27:26,911 - client_logger - ERROR - Connection failed: Error: [WinError 10061] No connection could be made because the target machine actively refused it [File: client_tcp.py, Line: 42, Function: connect]
2024-10-31 11:27:27,324 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 35, Function: main]
2024-10-31 11:27:27,332 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-31 11:27:27,340 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-31 11:27:29,626 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-31 11:27:29,939 - server_logger - INFO - New client joined! ('127.0.0.1', 59373) [File: server_tcp.py, Line: 263, Function: server_socket_handaling]
2024-10-31 11:27:29,939 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-31 11:27:42,018 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59373) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:27:42,018 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:27:42,071 - client_logger - INFO - login was succsusful [File: client_tcp.py, Line: 130, Function: login]
2024-10-31 11:27:48,822 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59373) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:27:48,822 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:28:46,233 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59373) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:28:46,233 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:32:55,200 - client_test - INFO - error [File: client_tcp.py, Line: 195, Function: qustion_handaling]
2024-10-31 11:40:22,236 - client_test - ERROR - Failed to send message due to socket error. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 104, Function: build_and_send_message]
2024-10-31 11:40:22,239 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:40:22,241 - client_test - INFO - Logout sent to server. [File: client_tcp.py, Line: 157, Function: logout]
2024-10-31 11:40:22,243 - client_test - INFO - Client socket closed. [File: client_tcp.py, Line: 162, Function: logout]
2024-10-31 11:40:36,455 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 35, Function: main]
2024-10-31 11:40:36,460 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-31 11:40:40,435 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-31 11:40:41,704 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-31 11:40:55,279 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 39, Function: main]
2024-10-31 11:40:55,283 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-31 11:40:55,286 - server_logger - INFO - New client joined! ('127.0.0.1', 59543) [File: server_tcp.py, Line: 263, Function: server_socket_handaling]
2024-10-31 11:40:55,286 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-31 11:41:00,173 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59543) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:41:00,173 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:41:00,229 - client_logger - INFO - login was succsusful [File: client_tcp.py, Line: 130, Function: login]
2024-10-31 11:41:03,291 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59543) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:41:03,291 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:42:54,778 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59543) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 11:42:54,778 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 11:48:55,968 - client_test - ERROR - Failed to connect to 127.0.0.1:5678. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 70, Function: recv_message_and_parse]
2024-10-31 12:07:33,727 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 35, Function: main]
2024-10-31 12:07:33,732 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-31 12:07:37,066 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-31 12:07:40,117 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-31 12:07:53,268 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 39, Function: main]
2024-10-31 12:07:53,275 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-31 12:07:53,278 - server_logger - INFO - New client joined! ('127.0.0.1', 59952) [File: server_tcp.py, Line: 263, Function: server_socket_handaling]
2024-10-31 12:07:53,278 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-31 12:07:57,752 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59952) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 12:07:57,752 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 12:08:19,487 - client_logger - INFO - login was succsusful [File: client_tcp.py, Line: 130, Function: login]
2024-10-31 12:08:24,239 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59952) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 12:08:24,239 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 12:09:46,218 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 12:09:55,102 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 59952) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 12:13:05,265 - client_test - ERROR - Failed to connect to 127.0.0.1:5678. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 70, Function: recv_message_and_parse]
2024-10-31 12:13:59,819 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 35, Function: main]
2024-10-31 12:13:59,824 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-31 12:14:01,639 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-31 12:14:02,555 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-31 12:14:09,411 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 39, Function: main]
2024-10-31 12:14:09,411 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-31 12:14:09,413 - server_logger - INFO - New client joined! ('127.0.0.1', 60054) [File: server_tcp.py, Line: 263, Function: server_socket_handaling]
2024-10-31 12:14:09,412 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-31 12:14:14,129 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 60054) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 12:14:14,129 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 12:14:20,461 - client_logger - INFO - login was succsusful [File: client_tcp.py, Line: 130, Function: login]
2024-10-31 12:14:25,069 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 60054) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 12:14:25,069 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 12:16:28,887 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 60054) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 12:16:28,886 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 12:22:08,553 - client_test - ERROR - Failed to connect to 127.0.0.1:5678. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 70, Function: recv_message_and_parse]
2024-10-31 12:22:22,643 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 35, Function: main]
2024-10-31 12:22:22,647 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-31 12:22:24,688 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-31 12:22:39,688 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 35, Function: main]
2024-10-31 12:22:39,693 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-31 12:22:49,230 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-31 12:23:09,156 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-31 12:23:17,804 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 39, Function: main]
2024-10-31 12:23:17,811 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-31 12:23:17,816 - server_logger - INFO - New client joined! ('127.0.0.1', 60246) [File: server_tcp.py, Line: 263, Function: server_socket_handaling]
2024-10-31 12:23:17,816 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-31 12:23:21,571 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 60246) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 12:23:21,571 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 12:23:24,769 - client_logger - INFO - login was succsusful [File: client_tcp.py, Line: 130, Function: login]
2024-10-31 12:23:28,713 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 60246) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 12:23:28,713 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 12:24:16,940 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 60246) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 12:24:16,940 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 12:26:37,352 - client_test - ERROR - Failed to connect to 127.0.0.1:5678. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 70, Function: recv_message_and_parse]
2024-10-31 12:26:51,073 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 35, Function: main]
2024-10-31 12:26:51,081 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-31 12:26:52,760 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-31 12:26:53,338 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-31 12:27:00,099 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 39, Function: main]
2024-10-31 12:27:00,105 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-31 12:27:00,109 - server_logger - INFO - New client joined! ('127.0.0.1', 60328) [File: server_tcp.py, Line: 263, Function: server_socket_handaling]
2024-10-31 12:27:00,109 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-31 12:27:04,073 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 60328) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 12:27:04,073 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 12:27:05,621 - client_logger - INFO - login was succsusful [File: client_tcp.py, Line: 130, Function: login]
2024-10-31 12:27:09,057 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 60328) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 12:27:09,057 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 12:27:21,784 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 60328) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 12:27:21,784 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 12:28:43,652 - client_test - ERROR - Failed to connect to 127.0.0.1:5678. Error: [WinError 10054] An existing connection was forcibly closed by the remote host [File: client_tcp.py, Line: 70, Function: recv_message_and_parse]
2024-10-31 12:28:55,313 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 35, Function: main]
2024-10-31 12:28:55,318 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-10-31 12:28:57,101 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-10-31 12:28:57,601 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
2024-10-31 12:29:05,895 - Main_App_logger - INFO - starting new client... [File: main.py, Line: 39, Function: main]
2024-10-31 12:29:05,902 - client_logger - INFO - client initilized [File: client_tcp.py, Line: 24, Function: __init__]
2024-10-31 12:29:05,906 - server_logger - INFO - New client joined! ('127.0.0.1', 60370) [File: server_tcp.py, Line: 263, Function: server_socket_handaling]
2024-10-31 12:29:05,905 - client_logger - INFO - Connected to server successfully. [File: client_tcp.py, Line: 38, Function: connect]
2024-10-31 12:29:11,037 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 60370) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 12:29:11,037 - client_logger - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 12:29:14,077 - client_logger - INFO - login was succsusful [File: client_tcp.py, Line: 130, Function: login]
2024-10-31 12:29:18,133 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 60370) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 12:29:18,133 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 12:29:27,961 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 60370) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 12:29:27,961 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 12:30:14,804 - client_test - INFO - wronggg [File: client_tcp.py, Line: 215, Function: qustion_handaling]
2024-10-31 12:30:55,632 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 60370) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 12:30:55,631 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 12:31:00,115 - client_test - INFO - [server]: your score is :0 [File: client_tcp.py, Line: 176, Function: my_score]
2024-10-31 12:31:07,042 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 60370) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 12:31:07,042 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-10-31 12:31:09,220 - client_test - INFO - [server]: all users scores :
1. master:500
2. player1:100
3. test:0 [File: client_tcp.py, Line: 183, Function: high_score]
2024-10-31 12:31:20,593 - server_logger - INFO - Waiting to receive a message from client ('127.0.0.1', 60370) [File: server_tcp.py, Line: 269, Function: server_socket_handaling]
2024-10-31 12:31:20,592 - client_test - INFO - Attempt to build and send message ended. [File: client_tcp.py, Line: 107, Function: build_and_send_message]
2024-11-14 16:08:02,087 - Main_App_logger - INFO - Starting Server... [File: main.py, Line: 27, Function: main]
2024-11-14 16:08:02,104 - server_logger - INFO - starting up on 0.0.0.0 port 5678 [File: server_tcp.py, Line: 61, Function: setup_socket]
2024-11-14 16:08:02,210 - server_logger - INFO - users data base loaded successfully [File: server_tcp.py, Line: 63, Function: setup_socket]
2024-11-14 16:08:02,296 - server_logger - INFO - questions loaded successfully [File: server_tcp.py, Line: 65, Function: setup_socket]
